# netlify.toml
# Configuration for deploying a React app on Netlify.

[build]
  command = "npm run build" # Assumes a React app build script
  publish = "build"         # The directory to publish

[dev]
  command = "npm start"
  port = 3000
  publish = "build"

# Redirects all paths to index.html for client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Environment variables can be set in the Netlify UI.
# Set REACT_APP_API_URL = https://family-hub-app-backend.onrender.com